// Copyright 2015-2022 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
/* AUTOGENERATED using chanstringgen.py */

/* Not very nice looking but the standard preprocessor is not very powerful
 and we save some memory over doing this all at runtime */
/* Output Strings */


#if (NUM_USB_CHAN_OUT > 1-1)
    .outputChanStr_1          = ""
    #if (1 < I2S_CHANS_DAC+1)
        "Analogue 1"
    #endif
    #if ((1 < SPDIF_TX_INDEX+2+1) && (1 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (1 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(1 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(1 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((1 < ADAT_TX_INDEX+8+1) && (1 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((1 < SPDIF_TX_INDEX+2+1) && (1 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (1 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(1 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(1 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(1 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(1 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(1 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(1 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(1 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(1 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 2-1)
    .outputChanStr_2          = ""
    #if (2 < I2S_CHANS_DAC+1)
        "Analogue 2"
    #endif
    #if ((2 < SPDIF_TX_INDEX+2+1) && (2 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (2 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(2 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(2 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((2 < ADAT_TX_INDEX+8+1) && (2 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((2 < SPDIF_TX_INDEX+2+1) && (2 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (2 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(2 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(2 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(2 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(2 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(2 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(2 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(2 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(2 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 3-1)
    .outputChanStr_3          = ""
    #if (3 < I2S_CHANS_DAC+1)
        "Analogue 3"
    #endif
    #if ((3 < SPDIF_TX_INDEX+2+1) && (3 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (3 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(3 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(3 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((3 < ADAT_TX_INDEX+8+1) && (3 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((3 < SPDIF_TX_INDEX+2+1) && (3 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (3 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(3 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(3 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(3 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(3 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(3 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(3 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(3 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(3 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 4-1)
    .outputChanStr_4          = ""
    #if (4 < I2S_CHANS_DAC+1)
        "Analogue 4"
    #endif
    #if ((4 < SPDIF_TX_INDEX+2+1) && (4 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (4 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(4 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(4 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((4 < ADAT_TX_INDEX+8+1) && (4 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((4 < SPDIF_TX_INDEX+2+1) && (4 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (4 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(4 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(4 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(4 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(4 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(4 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(4 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(4 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(4 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 5-1)
    .outputChanStr_5          = ""
    #if (5 < I2S_CHANS_DAC+1)
        "Analogue 5"
    #endif
    #if ((5 < SPDIF_TX_INDEX+2+1) && (5 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (5 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(5 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(5 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((5 < ADAT_TX_INDEX+8+1) && (5 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((5 < SPDIF_TX_INDEX+2+1) && (5 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (5 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(5 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(5 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(5 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(5 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(5 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(5 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(5 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(5 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 6-1)
    .outputChanStr_6          = ""
    #if (6 < I2S_CHANS_DAC+1)
        "Analogue 6"
    #endif
    #if ((6 < SPDIF_TX_INDEX+2+1) && (6 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (6 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(6 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(6 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((6 < ADAT_TX_INDEX+8+1) && (6 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((6 < SPDIF_TX_INDEX+2+1) && (6 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (6 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(6 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(6 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(6 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(6 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(6 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(6 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(6 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(6 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 7-1)
    .outputChanStr_7          = ""
    #if (7 < I2S_CHANS_DAC+1)
        "Analogue 7"
    #endif
    #if ((7 < SPDIF_TX_INDEX+2+1) && (7 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (7 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(7 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(7 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((7 < ADAT_TX_INDEX+8+1) && (7 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((7 < SPDIF_TX_INDEX+2+1) && (7 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (7 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(7 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(7 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(7 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(7 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(7 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(7 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(7 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(7 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 8-1)
    .outputChanStr_8          = ""
    #if (8 < I2S_CHANS_DAC+1)
        "Analogue 8"
    #endif
    #if ((8 < SPDIF_TX_INDEX+2+1) && (8 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (8 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(8 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(8 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((8 < ADAT_TX_INDEX+8+1) && (8 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((8 < SPDIF_TX_INDEX+2+1) && (8 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (8 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(8 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(8 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(8 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(8 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(8 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(8 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(8 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(8 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 9-1)
    .outputChanStr_9          = ""
    #if (9 < I2S_CHANS_DAC+1)
        "Analogue 9"
    #endif
    #if ((9 < SPDIF_TX_INDEX+2+1) && (9 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (9 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(9 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(9 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((9 < ADAT_TX_INDEX+8+1) && (9 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((9 < SPDIF_TX_INDEX+2+1) && (9 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (9 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(9 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(9 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(9 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(9 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(9 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(9 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(9 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(9 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 10-1)
    .outputChanStr_10          = ""
    #if (10 < I2S_CHANS_DAC+1)
        "Analogue 10"
    #endif
    #if ((10 < SPDIF_TX_INDEX+2+1) && (10 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (10 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(10 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(10 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((10 < ADAT_TX_INDEX+8+1) && (10 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((10 < SPDIF_TX_INDEX+2+1) && (10 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (10 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(10 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(10 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(10 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(10 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(10 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(10 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(10 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(10 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 11-1)
    .outputChanStr_11          = ""
    #if (11 < I2S_CHANS_DAC+1)
        "Analogue 11"
    #endif
    #if ((11 < SPDIF_TX_INDEX+2+1) && (11 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (11 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(11 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(11 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((11 < ADAT_TX_INDEX+8+1) && (11 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((11 < SPDIF_TX_INDEX+2+1) && (11 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (11 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(11 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(11 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(11 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(11 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(11 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(11 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(11 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(11 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 12-1)
    .outputChanStr_12          = ""
    #if (12 < I2S_CHANS_DAC+1)
        "Analogue 12"
    #endif
    #if ((12 < SPDIF_TX_INDEX+2+1) && (12 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (12 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(12 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(12 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((12 < ADAT_TX_INDEX+8+1) && (12 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((12 < SPDIF_TX_INDEX+2+1) && (12 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (12 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(12 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(12 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(12 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(12 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(12 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(12 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(12 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(12 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 13-1)
    .outputChanStr_13          = ""
    #if (13 < I2S_CHANS_DAC+1)
        "Analogue 13"
    #endif
    #if ((13 < SPDIF_TX_INDEX+2+1) && (13 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (13 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(13 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(13 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((13 < ADAT_TX_INDEX+8+1) && (13 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((13 < SPDIF_TX_INDEX+2+1) && (13 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (13 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(13 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(13 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(13 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(13 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(13 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(13 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(13 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(13 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 14-1)
    .outputChanStr_14          = ""
    #if (14 < I2S_CHANS_DAC+1)
        "Analogue 14"
    #endif
    #if ((14 < SPDIF_TX_INDEX+2+1) && (14 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (14 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(14 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(14 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((14 < ADAT_TX_INDEX+8+1) && (14 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((14 < SPDIF_TX_INDEX+2+1) && (14 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (14 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(14 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(14 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(14 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(14 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(14 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(14 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(14 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(14 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 15-1)
    .outputChanStr_15          = ""
    #if (15 < I2S_CHANS_DAC+1)
        "Analogue 15"
    #endif
    #if ((15 < SPDIF_TX_INDEX+2+1) && (15 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (15 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(15 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(15 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((15 < ADAT_TX_INDEX+8+1) && (15 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((15 < SPDIF_TX_INDEX+2+1) && (15 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (15 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(15 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(15 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(15 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(15 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(15 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(15 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(15 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(15 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 16-1)
    .outputChanStr_16          = ""
    #if (16 < I2S_CHANS_DAC+1)
        "Analogue 16"
    #endif
    #if ((16 < SPDIF_TX_INDEX+2+1) && (16 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (16 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(16 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(16 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((16 < ADAT_TX_INDEX+8+1) && (16 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((16 < SPDIF_TX_INDEX+2+1) && (16 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (16 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(16 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(16 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(16 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(16 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(16 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(16 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(16 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(16 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 17-1)
    .outputChanStr_17          = ""
    #if (17 < I2S_CHANS_DAC+1)
        "Analogue 17"
    #endif
    #if ((17 < SPDIF_TX_INDEX+2+1) && (17 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (17 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(17 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(17 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((17 < ADAT_TX_INDEX+8+1) && (17 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((17 < SPDIF_TX_INDEX+2+1) && (17 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (17 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(17 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(17 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(17 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(17 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(17 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(17 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(17 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(17 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 18-1)
    .outputChanStr_18          = ""
    #if (18 < I2S_CHANS_DAC+1)
        "Analogue 18"
    #endif
    #if ((18 < SPDIF_TX_INDEX+2+1) && (18 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (18 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(18 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(18 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((18 < ADAT_TX_INDEX+8+1) && (18 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((18 < SPDIF_TX_INDEX+2+1) && (18 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (18 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(18 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(18 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(18 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(18 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(18 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(18 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(18 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(18 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 19-1)
    .outputChanStr_19          = ""
    #if (19 < I2S_CHANS_DAC+1)
        "Analogue 19"
    #endif
    #if ((19 < SPDIF_TX_INDEX+2+1) && (19 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (19 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(19 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(19 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((19 < ADAT_TX_INDEX+8+1) && (19 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((19 < SPDIF_TX_INDEX+2+1) && (19 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (19 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(19 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(19 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(19 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(19 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(19 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(19 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(19 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(19 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 20-1)
    .outputChanStr_20          = ""
    #if (20 < I2S_CHANS_DAC+1)
        "Analogue 20"
    #endif
    #if ((20 < SPDIF_TX_INDEX+2+1) && (20 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (20 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(20 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(20 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((20 < ADAT_TX_INDEX+8+1) && (20 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((20 < SPDIF_TX_INDEX+2+1) && (20 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (20 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(20 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(20 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(20 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(20 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(20 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(20 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(20 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(20 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 21-1)
    .outputChanStr_21          = ""
    #if (21 < I2S_CHANS_DAC+1)
        "Analogue 21"
    #endif
    #if ((21 < SPDIF_TX_INDEX+2+1) && (21 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (21 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(21 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(21 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((21 < ADAT_TX_INDEX+8+1) && (21 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((21 < SPDIF_TX_INDEX+2+1) && (21 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (21 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(21 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(21 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(21 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(21 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(21 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(21 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(21 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(21 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 22-1)
    .outputChanStr_22          = ""
    #if (22 < I2S_CHANS_DAC+1)
        "Analogue 22"
    #endif
    #if ((22 < SPDIF_TX_INDEX+2+1) && (22 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (22 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(22 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(22 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((22 < ADAT_TX_INDEX+8+1) && (22 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((22 < SPDIF_TX_INDEX+2+1) && (22 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (22 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(22 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(22 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(22 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(22 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(22 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(22 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(22 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(22 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 23-1)
    .outputChanStr_23          = ""
    #if (23 < I2S_CHANS_DAC+1)
        "Analogue 23"
    #endif
    #if ((23 < SPDIF_TX_INDEX+2+1) && (23 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (23 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(23 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(23 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((23 < ADAT_TX_INDEX+8+1) && (23 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((23 < SPDIF_TX_INDEX+2+1) && (23 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (23 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(23 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(23 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(23 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(23 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(23 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(23 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(23 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(23 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 24-1)
    .outputChanStr_24          = ""
    #if (24 < I2S_CHANS_DAC+1)
        "Analogue 24"
    #endif
    #if ((24 < SPDIF_TX_INDEX+2+1) && (24 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (24 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(24 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(24 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((24 < ADAT_TX_INDEX+8+1) && (24 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((24 < SPDIF_TX_INDEX+2+1) && (24 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (24 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(24 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(24 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(24 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(24 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(24 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(24 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(24 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(24 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 25-1)
    .outputChanStr_25          = ""
    #if (25 < I2S_CHANS_DAC+1)
        "Analogue 25"
    #endif
    #if ((25 < SPDIF_TX_INDEX+2+1) && (25 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (25 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(25 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(25 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((25 < ADAT_TX_INDEX+8+1) && (25 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((25 < SPDIF_TX_INDEX+2+1) && (25 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (25 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(25 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(25 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(25 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(25 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(25 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(25 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(25 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(25 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 26-1)
    .outputChanStr_26          = ""
    #if (26 < I2S_CHANS_DAC+1)
        "Analogue 26"
    #endif
    #if ((26 < SPDIF_TX_INDEX+2+1) && (26 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (26 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(26 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(26 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((26 < ADAT_TX_INDEX+8+1) && (26 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((26 < SPDIF_TX_INDEX+2+1) && (26 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (26 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(26 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(26 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(26 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(26 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(26 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(26 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(26 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(26 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 27-1)
    .outputChanStr_27          = ""
    #if (27 < I2S_CHANS_DAC+1)
        "Analogue 27"
    #endif
    #if ((27 < SPDIF_TX_INDEX+2+1) && (27 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (27 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(27 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(27 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((27 < ADAT_TX_INDEX+8+1) && (27 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((27 < SPDIF_TX_INDEX+2+1) && (27 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (27 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(27 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(27 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(27 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(27 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(27 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(27 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(27 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(27 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 28-1)
    .outputChanStr_28          = ""
    #if (28 < I2S_CHANS_DAC+1)
        "Analogue 28"
    #endif
    #if ((28 < SPDIF_TX_INDEX+2+1) && (28 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (28 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(28 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(28 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((28 < ADAT_TX_INDEX+8+1) && (28 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((28 < SPDIF_TX_INDEX+2+1) && (28 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (28 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(28 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(28 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(28 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(28 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(28 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(28 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(28 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(28 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 29-1)
    .outputChanStr_29          = ""
    #if (29 < I2S_CHANS_DAC+1)
        "Analogue 29"
    #endif
    #if ((29 < SPDIF_TX_INDEX+2+1) && (29 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (29 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(29 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(29 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((29 < ADAT_TX_INDEX+8+1) && (29 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((29 < SPDIF_TX_INDEX+2+1) && (29 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (29 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(29 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(29 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(29 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(29 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(29 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(29 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(29 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(29 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 30-1)
    .outputChanStr_30          = ""
    #if (30 < I2S_CHANS_DAC+1)
        "Analogue 30"
    #endif
    #if ((30 < SPDIF_TX_INDEX+2+1) && (30 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (30 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(30 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(30 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((30 < ADAT_TX_INDEX+8+1) && (30 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((30 < SPDIF_TX_INDEX+2+1) && (30 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (30 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(30 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(30 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(30 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(30 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(30 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(30 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(30 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(30 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 31-1)
    .outputChanStr_31          = ""
    #if (31 < I2S_CHANS_DAC+1)
        "Analogue 31"
    #endif
    #if ((31 < SPDIF_TX_INDEX+2+1) && (31 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (31 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(31 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(31 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((31 < ADAT_TX_INDEX+8+1) && (31 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((31 < SPDIF_TX_INDEX+2+1) && (31 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (31 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(31 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(31 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(31 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(31 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(31 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(31 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(31 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(31 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_OUT > 32-1)
    .outputChanStr_32          = ""
    #if (32 < I2S_CHANS_DAC+1)
        "Analogue 32"
    #endif
    #if ((32 < SPDIF_TX_INDEX+2+1) && (32 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN)
        #if (32 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(32 - SPDIF_TX_INDEX == 1)
            "SPDIF 1"
        #elif(32 - SPDIF_TX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((32 < ADAT_TX_INDEX+8+1) && (32 > ADAT_TX_INDEX)) && (XUA_ADAT_TX_EN)
        #if ((32 < SPDIF_TX_INDEX+2+1) && (32 > SPDIF_TX_INDEX)) && (XUA_SPDIF_TX_EN) || (32 < I2S_CHANS_DAC+1)
        "/"
        #endif
        #if(32 - ADAT_TX_INDEX == 1)
            "ADAT 1"
        #elif(32 - ADAT_TX_INDEX == 2)
            "ADAT 2"
        #elif(32 - ADAT_TX_INDEX == 3)
            "ADAT 3"
        #elif(32 - ADAT_TX_INDEX == 4)
            "ADAT 4"
        #elif(32 - ADAT_TX_INDEX == 5)
            "ADAT 5"
        #elif(32 - ADAT_TX_INDEX == 6)
            "ADAT 6"
        #elif(32 - ADAT_TX_INDEX == 7)
            "ADAT 7"
        #elif(32 - ADAT_TX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

/* Input Strings */


#if (NUM_USB_CHAN_IN > 1-1)
    .inputChanStr_1          = ""
    #if (1 < I2S_CHANS_ADC+1)
        "Analogue 1"
    #endif
    #if ((1 < SPDIF_RX_INDEX+2+1) && (1 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (1 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(1 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(1 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((1 < ADAT_RX_INDEX+8+1) && (1 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((1 < SPDIF_RX_INDEX+2+1) && (1 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (1 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(1 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(1 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(1 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(1 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(1 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(1 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(1 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(1 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 2-1)
    .inputChanStr_2          = ""
    #if (2 < I2S_CHANS_ADC+1)
        "Analogue 2"
    #endif
    #if ((2 < SPDIF_RX_INDEX+2+1) && (2 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (2 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(2 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(2 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((2 < ADAT_RX_INDEX+8+1) && (2 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((2 < SPDIF_RX_INDEX+2+1) && (2 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (2 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(2 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(2 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(2 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(2 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(2 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(2 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(2 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(2 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 3-1)
    .inputChanStr_3          = ""
    #if (3 < I2S_CHANS_ADC+1)
        "Analogue 3"
    #endif
    #if ((3 < SPDIF_RX_INDEX+2+1) && (3 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (3 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(3 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(3 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((3 < ADAT_RX_INDEX+8+1) && (3 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((3 < SPDIF_RX_INDEX+2+1) && (3 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (3 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(3 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(3 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(3 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(3 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(3 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(3 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(3 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(3 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 4-1)
    .inputChanStr_4          = ""
    #if (4 < I2S_CHANS_ADC+1)
        "Analogue 4"
    #endif
    #if ((4 < SPDIF_RX_INDEX+2+1) && (4 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (4 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(4 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(4 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((4 < ADAT_RX_INDEX+8+1) && (4 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((4 < SPDIF_RX_INDEX+2+1) && (4 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (4 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(4 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(4 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(4 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(4 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(4 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(4 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(4 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(4 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 5-1)
    .inputChanStr_5          = ""
    #if (5 < I2S_CHANS_ADC+1)
        "Analogue 5"
    #endif
    #if ((5 < SPDIF_RX_INDEX+2+1) && (5 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (5 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(5 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(5 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((5 < ADAT_RX_INDEX+8+1) && (5 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((5 < SPDIF_RX_INDEX+2+1) && (5 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (5 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(5 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(5 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(5 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(5 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(5 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(5 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(5 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(5 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 6-1)
    .inputChanStr_6          = ""
    #if (6 < I2S_CHANS_ADC+1)
        "Analogue 6"
    #endif
    #if ((6 < SPDIF_RX_INDEX+2+1) && (6 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (6 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(6 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(6 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((6 < ADAT_RX_INDEX+8+1) && (6 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((6 < SPDIF_RX_INDEX+2+1) && (6 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (6 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(6 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(6 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(6 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(6 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(6 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(6 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(6 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(6 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 7-1)
    .inputChanStr_7          = ""
    #if (7 < I2S_CHANS_ADC+1)
        "Analogue 7"
    #endif
    #if ((7 < SPDIF_RX_INDEX+2+1) && (7 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (7 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(7 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(7 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((7 < ADAT_RX_INDEX+8+1) && (7 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((7 < SPDIF_RX_INDEX+2+1) && (7 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (7 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(7 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(7 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(7 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(7 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(7 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(7 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(7 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(7 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 8-1)
    .inputChanStr_8          = ""
    #if (8 < I2S_CHANS_ADC+1)
        "Analogue 8"
    #endif
    #if ((8 < SPDIF_RX_INDEX+2+1) && (8 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (8 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(8 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(8 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((8 < ADAT_RX_INDEX+8+1) && (8 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((8 < SPDIF_RX_INDEX+2+1) && (8 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (8 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(8 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(8 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(8 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(8 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(8 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(8 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(8 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(8 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 9-1)
    .inputChanStr_9          = ""
    #if (9 < I2S_CHANS_ADC+1)
        "Analogue 9"
    #endif
    #if ((9 < SPDIF_RX_INDEX+2+1) && (9 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (9 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(9 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(9 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((9 < ADAT_RX_INDEX+8+1) && (9 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((9 < SPDIF_RX_INDEX+2+1) && (9 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (9 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(9 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(9 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(9 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(9 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(9 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(9 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(9 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(9 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 10-1)
    .inputChanStr_10          = ""
    #if (10 < I2S_CHANS_ADC+1)
        "Analogue 10"
    #endif
    #if ((10 < SPDIF_RX_INDEX+2+1) && (10 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (10 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(10 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(10 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((10 < ADAT_RX_INDEX+8+1) && (10 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((10 < SPDIF_RX_INDEX+2+1) && (10 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (10 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(10 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(10 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(10 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(10 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(10 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(10 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(10 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(10 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 11-1)
    .inputChanStr_11          = ""
    #if (11 < I2S_CHANS_ADC+1)
        "Analogue 11"
    #endif
    #if ((11 < SPDIF_RX_INDEX+2+1) && (11 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (11 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(11 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(11 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((11 < ADAT_RX_INDEX+8+1) && (11 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((11 < SPDIF_RX_INDEX+2+1) && (11 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (11 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(11 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(11 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(11 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(11 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(11 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(11 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(11 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(11 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 12-1)
    .inputChanStr_12          = ""
    #if (12 < I2S_CHANS_ADC+1)
        "Analogue 12"
    #endif
    #if ((12 < SPDIF_RX_INDEX+2+1) && (12 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (12 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(12 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(12 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((12 < ADAT_RX_INDEX+8+1) && (12 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((12 < SPDIF_RX_INDEX+2+1) && (12 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (12 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(12 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(12 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(12 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(12 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(12 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(12 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(12 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(12 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 13-1)
    .inputChanStr_13          = ""
    #if (13 < I2S_CHANS_ADC+1)
        "Analogue 13"
    #endif
    #if ((13 < SPDIF_RX_INDEX+2+1) && (13 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (13 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(13 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(13 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((13 < ADAT_RX_INDEX+8+1) && (13 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((13 < SPDIF_RX_INDEX+2+1) && (13 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (13 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(13 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(13 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(13 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(13 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(13 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(13 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(13 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(13 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 14-1)
    .inputChanStr_14          = ""
    #if (14 < I2S_CHANS_ADC+1)
        "Analogue 14"
    #endif
    #if ((14 < SPDIF_RX_INDEX+2+1) && (14 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (14 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(14 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(14 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((14 < ADAT_RX_INDEX+8+1) && (14 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((14 < SPDIF_RX_INDEX+2+1) && (14 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (14 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(14 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(14 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(14 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(14 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(14 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(14 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(14 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(14 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 15-1)
    .inputChanStr_15          = ""
    #if (15 < I2S_CHANS_ADC+1)
        "Analogue 15"
    #endif
    #if ((15 < SPDIF_RX_INDEX+2+1) && (15 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (15 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(15 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(15 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((15 < ADAT_RX_INDEX+8+1) && (15 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((15 < SPDIF_RX_INDEX+2+1) && (15 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (15 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(15 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(15 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(15 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(15 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(15 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(15 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(15 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(15 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 16-1)
    .inputChanStr_16          = ""
    #if (16 < I2S_CHANS_ADC+1)
        "Analogue 16"
    #endif
    #if ((16 < SPDIF_RX_INDEX+2+1) && (16 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (16 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(16 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(16 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((16 < ADAT_RX_INDEX+8+1) && (16 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((16 < SPDIF_RX_INDEX+2+1) && (16 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (16 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(16 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(16 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(16 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(16 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(16 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(16 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(16 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(16 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 17-1)
    .inputChanStr_17          = ""
    #if (17 < I2S_CHANS_ADC+1)
        "Analogue 17"
    #endif
    #if ((17 < SPDIF_RX_INDEX+2+1) && (17 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (17 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(17 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(17 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((17 < ADAT_RX_INDEX+8+1) && (17 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((17 < SPDIF_RX_INDEX+2+1) && (17 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (17 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(17 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(17 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(17 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(17 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(17 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(17 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(17 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(17 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 18-1)
    .inputChanStr_18          = ""
    #if (18 < I2S_CHANS_ADC+1)
        "Analogue 18"
    #endif
    #if ((18 < SPDIF_RX_INDEX+2+1) && (18 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (18 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(18 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(18 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((18 < ADAT_RX_INDEX+8+1) && (18 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((18 < SPDIF_RX_INDEX+2+1) && (18 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (18 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(18 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(18 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(18 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(18 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(18 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(18 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(18 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(18 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 19-1)
    .inputChanStr_19          = ""
    #if (19 < I2S_CHANS_ADC+1)
        "Analogue 19"
    #endif
    #if ((19 < SPDIF_RX_INDEX+2+1) && (19 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (19 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(19 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(19 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((19 < ADAT_RX_INDEX+8+1) && (19 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((19 < SPDIF_RX_INDEX+2+1) && (19 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (19 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(19 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(19 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(19 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(19 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(19 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(19 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(19 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(19 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 20-1)
    .inputChanStr_20          = ""
    #if (20 < I2S_CHANS_ADC+1)
        "Analogue 20"
    #endif
    #if ((20 < SPDIF_RX_INDEX+2+1) && (20 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (20 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(20 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(20 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((20 < ADAT_RX_INDEX+8+1) && (20 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((20 < SPDIF_RX_INDEX+2+1) && (20 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (20 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(20 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(20 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(20 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(20 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(20 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(20 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(20 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(20 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 21-1)
    .inputChanStr_21          = ""
    #if (21 < I2S_CHANS_ADC+1)
        "Analogue 21"
    #endif
    #if ((21 < SPDIF_RX_INDEX+2+1) && (21 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (21 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(21 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(21 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((21 < ADAT_RX_INDEX+8+1) && (21 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((21 < SPDIF_RX_INDEX+2+1) && (21 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (21 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(21 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(21 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(21 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(21 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(21 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(21 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(21 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(21 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 22-1)
    .inputChanStr_22          = ""
    #if (22 < I2S_CHANS_ADC+1)
        "Analogue 22"
    #endif
    #if ((22 < SPDIF_RX_INDEX+2+1) && (22 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (22 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(22 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(22 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((22 < ADAT_RX_INDEX+8+1) && (22 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((22 < SPDIF_RX_INDEX+2+1) && (22 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (22 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(22 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(22 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(22 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(22 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(22 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(22 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(22 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(22 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 23-1)
    .inputChanStr_23          = ""
    #if (23 < I2S_CHANS_ADC+1)
        "Analogue 23"
    #endif
    #if ((23 < SPDIF_RX_INDEX+2+1) && (23 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (23 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(23 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(23 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((23 < ADAT_RX_INDEX+8+1) && (23 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((23 < SPDIF_RX_INDEX+2+1) && (23 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (23 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(23 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(23 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(23 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(23 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(23 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(23 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(23 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(23 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 24-1)
    .inputChanStr_24          = ""
    #if (24 < I2S_CHANS_ADC+1)
        "Analogue 24"
    #endif
    #if ((24 < SPDIF_RX_INDEX+2+1) && (24 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (24 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(24 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(24 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((24 < ADAT_RX_INDEX+8+1) && (24 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((24 < SPDIF_RX_INDEX+2+1) && (24 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (24 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(24 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(24 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(24 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(24 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(24 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(24 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(24 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(24 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 25-1)
    .inputChanStr_25          = ""
    #if (25 < I2S_CHANS_ADC+1)
        "Analogue 25"
    #endif
    #if ((25 < SPDIF_RX_INDEX+2+1) && (25 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (25 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(25 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(25 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((25 < ADAT_RX_INDEX+8+1) && (25 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((25 < SPDIF_RX_INDEX+2+1) && (25 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (25 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(25 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(25 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(25 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(25 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(25 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(25 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(25 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(25 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 26-1)
    .inputChanStr_26          = ""
    #if (26 < I2S_CHANS_ADC+1)
        "Analogue 26"
    #endif
    #if ((26 < SPDIF_RX_INDEX+2+1) && (26 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (26 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(26 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(26 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((26 < ADAT_RX_INDEX+8+1) && (26 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((26 < SPDIF_RX_INDEX+2+1) && (26 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (26 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(26 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(26 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(26 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(26 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(26 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(26 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(26 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(26 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 27-1)
    .inputChanStr_27          = ""
    #if (27 < I2S_CHANS_ADC+1)
        "Analogue 27"
    #endif
    #if ((27 < SPDIF_RX_INDEX+2+1) && (27 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (27 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(27 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(27 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((27 < ADAT_RX_INDEX+8+1) && (27 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((27 < SPDIF_RX_INDEX+2+1) && (27 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (27 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(27 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(27 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(27 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(27 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(27 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(27 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(27 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(27 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 28-1)
    .inputChanStr_28          = ""
    #if (28 < I2S_CHANS_ADC+1)
        "Analogue 28"
    #endif
    #if ((28 < SPDIF_RX_INDEX+2+1) && (28 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (28 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(28 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(28 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((28 < ADAT_RX_INDEX+8+1) && (28 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((28 < SPDIF_RX_INDEX+2+1) && (28 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (28 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(28 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(28 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(28 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(28 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(28 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(28 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(28 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(28 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 29-1)
    .inputChanStr_29          = ""
    #if (29 < I2S_CHANS_ADC+1)
        "Analogue 29"
    #endif
    #if ((29 < SPDIF_RX_INDEX+2+1) && (29 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (29 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(29 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(29 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((29 < ADAT_RX_INDEX+8+1) && (29 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((29 < SPDIF_RX_INDEX+2+1) && (29 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (29 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(29 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(29 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(29 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(29 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(29 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(29 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(29 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(29 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 30-1)
    .inputChanStr_30          = ""
    #if (30 < I2S_CHANS_ADC+1)
        "Analogue 30"
    #endif
    #if ((30 < SPDIF_RX_INDEX+2+1) && (30 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (30 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(30 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(30 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((30 < ADAT_RX_INDEX+8+1) && (30 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((30 < SPDIF_RX_INDEX+2+1) && (30 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (30 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(30 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(30 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(30 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(30 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(30 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(30 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(30 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(30 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 31-1)
    .inputChanStr_31          = ""
    #if (31 < I2S_CHANS_ADC+1)
        "Analogue 31"
    #endif
    #if ((31 < SPDIF_RX_INDEX+2+1) && (31 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (31 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(31 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(31 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((31 < ADAT_RX_INDEX+8+1) && (31 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((31 < SPDIF_RX_INDEX+2+1) && (31 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (31 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(31 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(31 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(31 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(31 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(31 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(31 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(31 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(31 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

#if (NUM_USB_CHAN_IN > 32-1)
    .inputChanStr_32          = ""
    #if (32 < I2S_CHANS_ADC+1)
        "Analogue 32"
    #endif
    #if ((32 < SPDIF_RX_INDEX+2+1) && (32 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN)
        #if (32 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(32 - SPDIF_RX_INDEX == 1)
            "SPDIF 1"
        #elif(32 - SPDIF_RX_INDEX == 2)
            "SPDIF 2"
        #endif
    #endif
    #if ((32 < ADAT_RX_INDEX+8+1) && (32 > ADAT_RX_INDEX)) && (XUA_ADAT_RX_EN)
        #if ((32 < SPDIF_RX_INDEX+2+1) && (32 > SPDIF_RX_INDEX)) && (XUA_SPDIF_RX_EN) || (32 < I2S_CHANS_ADC+1)
        "/"
        #endif
        #if(32 - ADAT_RX_INDEX == 1)
            "ADAT 1"
        #elif(32 - ADAT_RX_INDEX == 2)
            "ADAT 2"
        #elif(32 - ADAT_RX_INDEX == 3)
            "ADAT 3"
        #elif(32 - ADAT_RX_INDEX == 4)
            "ADAT 4"
        #elif(32 - ADAT_RX_INDEX == 5)
            "ADAT 5"
        #elif(32 - ADAT_RX_INDEX == 6)
            "ADAT 6"
        #elif(32 - ADAT_RX_INDEX == 7)
            "ADAT 7"
        #elif(32 - ADAT_RX_INDEX == 8)
            "ADAT 8"
        #endif
     #endif
        ,
#endif

